//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInvoiceDetail
    {
        public int AccountInvoiceDetailID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int LocationID { get; set; }
        public int AccountInvoiceID { get; set; }
        public int CustomerID { get; set; }
        public int SalesInvoiceDetailID { get; set; }
        public string Remarks { get; set; }
    
        public virtual AccountInvoice AccountInvoice { get; set; }
        public virtual SalesInvoiceDetail SalesInvoiceDetail { get; set; }
    }
}
