//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class GoodsReceiptIndex
    {
        public string LocationCode { get; set; }
        public int GoodsReceiptID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Reference { get; set; }
        public decimal TotalQuantity { get; set; }
        public string VoucherType { get; set; }
        public string VoucherReference { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string VoucherOwner { get; set; }
        public string Description { get; set; }
    }
}
