//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryAdjustment
    {
        public InventoryAdjustment()
        {
            this.InventoryAdjustmentDetails = new HashSet<InventoryAdjustmentDetail>();
        }
    
        public int InventoryAdjustmentID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
        public int SupplierID { get; set; }
        public int InventoryAdjustmentTypeID { get; set; }
        public int EmployeeID { get; set; }
        public int UserID { get; set; }
        public int PreparedPersonID { get; set; }
        public int OrganizationalUnitID { get; set; }
        public int LocationID { get; set; }
        public int ApproverID { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TotalVATAmount { get; set; }
        public decimal TotalGrossAmount { get; set; }
        public string MemoNo { get; set; }
        public System.DateTime MemoDate { get; set; }
        public string MemoJob { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EditedDate { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool InActive { get; set; }
        public bool InActivePartial { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<InventoryAdjustmentDetail> InventoryAdjustmentDetails { get; set; }
        public virtual InventoryAdjustmentType InventoryAdjustmentType { get; set; }
        public virtual Location Location { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
