//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public Promotion()
        {
            this.SalesInvoices = new HashSet<SalesInvoice>();
        }
    
        public int PromotionID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
    }
}
