//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class VehicleTransferIndex
    {
        public string LocationCode { get; set; }
        public int StockTransferID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Reference { get; set; }
        public string WarehouseCode { get; set; }
        public decimal TotalQuantity { get; set; }
        public string Description { get; set; }
        public string TransferOrderReference { get; set; }
        public Nullable<System.DateTime> TransferOrderEntryDate { get; set; }
        public Nullable<System.DateTime> TransferOrderRequestedDate { get; set; }
    }
}
